from midiutil import MIDIFile
# Gene name must be entered with underscore instead of space. Don't forget the quotes!
GENE_NAME = "HO_Endonuclease"
nucleotide_to_midi = {'A': 60, 'T': 64, 'C': 67, 'G': 72}
protein_to_midi = {
    'A': 48, 'R': 52, 'N': 55, 'D': 36, 'C': 48, 'Q': 52, 'E': 55, 'G': 36,'H': 48, 'I': 52, 'L': 55, 'K': 36, 'M': 48, 'F': 52, 'P': 55, 'S': 36, 'T': 48, 'W': 52,
    'Y': 55, 'V': 36, 'O': 48, 'U': 52}
# Copy and paste the coding sequence (in single-stranded FASTA format) of your favorite gene within the quotes minus the last three nucleotides (the stop codon).
sequence = "ATGCTTTCTGAAAACACGACTATTCTGATGGCTAACGGTGAAATTAAAGACATCGCAAACGTCACGGCTAACTCTTACGTTATGTGCGCAGATGGCTCCGCTGCCCGCGTCATAAATGTCACACAGGGCTATCAGAAAATCTATAATATACAGCAAAAAACCAAACACAGAGCTTTTGAAGGTGAACCTGGTAGGTTAGATCCCAGGCGTAGAACAGTTTATCAGCGTCTTGCATTACAATGTACTGCAGGTCATAAATTGTCAGTCAGGGTCCCTACCAAACCACTGTTGGAAAAAAGTGGTAGAAATGCCACCAAATATAAAGTGAGATGGAGAAATCTGCAGCAATGTCAGACGCTTGATGGTAGGATAATAATAATTCCAAAAAACCATCATAAGACATTCCCAATGACAGTTGAAGGTGAGTTTGCCGCAAAACGCTTCATAGAAGAAATGGAGCGCTCTAAAGGAGAATATTTCAACTTTGACATTGAAGTTAGAGATTTGGATTATCTTGATGCTCAATTGAGAATTTCTAGCTGCATAAGATTTGGTCCAGTACTCGCAGGAAATGGTGTTTTATCTAAATTTCTCACTGGACGTAGTGACCTTGTAACTCCTGCTGTAAAAAGTATGGCTTGGATGCTTGGTCTGTGGTTAGGTGACAGTACAACAAAAGAGCCAGAAATCTCAGTAGATAGCTTGGATCCTAAGCTAATGGAGAGTTTAAGAGAAAATGCGAAAATCTGGGGTCTCTACCTTACGGTTTGTGACGATCACGTTCCGCTACGTGCCAAACATGTAAGGCTTCATTATGGAGATGGTCCAGATGAAAACAGGAAGACAAGGAATTTGAGGAAAAATAATCCATTCTGGAAAGCTGTCACAATTTTAAAGTTTAAAAGGGATCTTGATGGAGAGAAGCAAATCCCTGAATTTATGTACGGCGAGCATATAGAAGTTCGTGAAGCATTCTTAGCCGGCTTGATCGACTCAGATGGGTACGTTGTGAAAAAGGGCGAAGGCCCTGAATCTTATAAAATAGCAATTCAAACTGTTTATTCATCCATTATGGACGGAATTGTCCATATTTCAAGATCTCTTGGTATGTCAGCTACTGTGACGACCAGGTCAGCTAGGGAGGAAATCATTGAAGGAAGAAAAGTCCAATGTCAATTTACATACGACTGTAATGTTGCTGGGGGAACAACTTCACAGAATGTTTTGTCATATTGTCGAAGTGGTCACAAAACAAGAGAAGTTCCGCCAATTATAAAAAGGGAACCCGTATATTTCAGCTTCACGGATGATTTCCAGGGTGAGAGTACTGTATATGGGCTTACGATAGAAGGCCATAAAAATTTCTTGCTTGGCAACAAAATAGAAGTGAAATCATGTCGAGGCTGCTGTGTGGGAGAACAGCTTAAAATATCACAAAAAAAGAATCTAAAACACTGTGTTGCTTGTCCCAGAAAGGGAATCAAGTATTTTTATAAAGATTGGAGTGGTAAAAATCGAGTATGTGCTAGATGCTATGGAAGATACAAATTCAGCGGTCATCACTGTATAAATTGCAAGTATGTACCAGAAGCACGTGAAGTGAAAAAGGCAAAAGACAAAGGCGAAAAATTGGGCATTACGCCCGAAGGTTTGCCAGTTAAAGGACCAGAGTGTATAAAATGTGGCGGAATCTTACAGTTTGATGCTGTCCGCGGGCCTCATAAGAGTTGTGGTAACAACGCAGGTGCGCGCATCTGC"
# Copy and paste within the quotes, the amino acid abbreviations for the coding sequence. Do not include the asterisk!
protein = "MLSENTTILMANGEIKDIANVTANSYVMCADGSAARVINVTQGYQKIYNIQQKTKHRAFEGEPGRLDPRRRTVYQRLALQCTAGHKLSVRVPTKPLLEKSGRNATKYKVRWRNLQQCQTLDGRIIIIPKNHHKTFPMTVEGEFAAKRFIEEMERSKGEYFNFDIEVRDLDYLDAQLRISSCIRFGPVLAGNGVLSKFLTGRSDLVTPAVKSMAWMLGLWLGDSTTKEPEISVDSLDPKLMESLRENAKIWGLYLTVCDDHVPLRAKHVRLHYGDGPDENRKTRNLRKNNPFWKAVTILKFKRDLDGEKQIPEFMYGEHIEVREAFLAGLIDSDGYVVKKGEGPESYKIAIQTVYSSIMDGIVHISRSLGMSATVTTRSAREEIIEGRKVQCQFTYDCNVAGGTTSQNVLSYCRSGHKTREVPPIIKREPVYFSFTDDFQGESTVYGLTIEGHKNFLLGNKIEVKSCRGCCVGEQLKISQKKNLKHCVACPRKGIKYFYKDWSGKNRVCARCYGRYKFSGHHCINCKYVPEAREVKKAKDKGEKLGITPEGLPVKGPECIKCGGILQFDAVRGPHKSCGNNAGARIC"
TEMPO = 180 #Change this tempo if you want to end the cacophony more quickly

def main ():
    midi = MIDIFile(2) #This makes 2 tracks which will play simultaneously. Tracks are numbered zero and one.
    midi.addTempo(0, 0, TEMPO)
    midi.addTempo(1, 0, TEMPO)
    dna_duration = len(protein) / len(sequence)  # 0.333 beats #This synchronizes the DNA sequence to finish at the same time as the protein
    protein_duration = 1  # 1 beat
    output_filename = f"{GENE_NAME}.mid"
    
       
    midi.addTrackName(0, 0, "DNA")
    for i, nucleotide in enumerate(sequence):
        note = nucleotide_to_midi.get(nucleotide)
        volume = 100  
        if note:
            midi.addNote(0, 0, note, i * dna_duration, dna_duration, 100)

    track_protein = 1
    midi.addTrackName(1, 0, "Protein")
    for i, amino_acid in enumerate(protein):
        note = protein_to_midi.get(amino_acid)
        if note:
            midi.addNote(1, 0, note, i * protein_duration, protein_duration, 100)
    with open(output_filename, "wb") as output_file:
        midi.writeFile(output_file)

if __name__ == "__main__":
    main()